// vue-image-search/src/App.vue
<template>
  <div id="app">
    <h1>{{title}}</h1>
    <form @submit.prevent="formSubmitted()">
        <label for="searchTerm">Search Term</label>
        <input v-model="searchTerm" class="u-full-width" type="text" id="searchTerm" name="searchTerm" autocomplete="off">
        <button type="submit">Search</button>
    </form>
    <img v-if="loading" id="loadingImage" src="https://i.imgur.com/LVHmLnb.gif" alt="loading ice cream image">
    <section class="images">
      <img v-for="image in images" :key="image.id" :src="image.urls.small" :alt="image.alt_description">
    </section>
  </div>
</template>

<script>
import API from './API';

export default {
  name: 'app',
  data() {
    return {
      title: 'Vue Image Search',
      searchTerm: '',
      images: [],
      loading: false,
    };
  },
  methods: {
    formSubmitted() {
      this.loading = true;
      this.images = [];
      API.search(this.searchTerm)
        .then((images) => {
          this.images = images;
          this.loading = false;
        });
    },
  },
};
</script>

<style>
  body {
    width: 80%;
    margin: 2em auto 0 auto;
  }

  h1 {
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .images {
    column-count: 3;
  }

  img {
    width: 100%;
  }
</style>

// react-image-search/src/App.js
import React from 'react';
import API from './API';

class App extends React.Component {
  constructor() {
    super()
    this.state = {
      title: 'React Image Search',
      searchTerm: '',
      loading: false,
      images: []
    };
  }

  formSubmitted(event) {
    event.preventDefault();

    this.setState({
      loading: true,
      images: []
    })

    API.search(this.state.searchTerm)
      .then(images => {
        this.setState({
          loading: false,
          images
        })
      })
  }

  searchTermChanged(event) {
    this.setState({
      searchTerm: event.target.value
    })
  }

  render() {
    const { title, searchTerm, loading, images } = this.state; // destructuring
    return (
      <div>
        <h1>{title}</h1>
        <form onSubmit={(event) => this.formSubmitted(event)}>
          <label htmlFor="searchTerm">Search Term</label>
          <input onChange={(event) => this.searchTermChanged(event)} value={searchTerm} className="u-full-width" type="text" id="searchTerm" name="searchTerm" autoComplete="off" />
          <button type="submit">Search</button>
        </form>
        {loading ? <img src="https://i.imgur.com/LVHmLnb.gif" alt="loading ice cream"></img> : ''}
        <section className="images">
          {images.map((image, i) => {
            return <img key={image.id} alt={image.alt_description} src={image.urls.small}/>
          })}
        </section>
      </div>
    );
  }
}

export default App;
